### ISSUE TITLE
DoubleShellChain: LogNorm distrib. on param **n** gives error for n<=0 even if n is far from 0

### ISSUE THREAD

**Issue by ibressler** [SASfit/SASfit#11]
- LogNorm distrib. on DoubleShellChain param **n** gives error even for reasonable params far from **mu=0**
  ```
  #form factor: can not calculate
  value of 16 diff 0
  .../sasfit_ff_doubleshellchain.c:38: Can not calculate form factor because n(0) <= 0 !
  ```

**Comment by Kohlbrecher** [comment]
A lognormal integration likely integrates from 0 to max value. The lower intergration limit 0 causes this issue.

**Comment by ibressler** [comment]
Yes, but the problem is with values above 0, tested with a very narrow distribution around, lets say 10 or so ...
I have to admit, I did not check the latest development version. The problem was mainly with the stable version 0.94.11:

![Screenshot 2022-04-08 at 17 26 04](https://user-images.githubusercontent.com/638052/162475010-a5e64891-0069-454d-8172-156dd8265f52.png)

Whereas the latest development version gives more detailed error messages about unexpected parameter values (see SASfit console in screenshots with error message from previous runs). Once they are satisfied, the curve is calculated and plotted with the given LogNorm parameters - which did not work in 0.94.11 above.

![Screenshot 2022-04-08 at 17 42 16](https://user-images.githubusercontent.com/638052/162476408-42c05803-aab1-4fea-858e-ef5653c7ccb7.png)

Therefore, I consider this issue as fixed and close it.
It's archived here, in case someone stumbles across this problem in the future.
