### ISSUE TITLE
Discrepency between sasmodels and SASFit

### ISSUE THREAD

**Issue by kiranvad** [SASfit/SASfit#19]
Hello,

Does SASFit perform any volume normalization of polymer micelle models? I am unable to find any information on this in the manual. Detailed description with an example below.

----------------------

I am trying to match some of my custom implementations of polymer micelles in sasmodels with SASFit. I cannot get my head around the following consistent behavior I see across different simulations.
My implementations match fairly well in terms of shape but are off by some form of pre-factor or volume normalization. I want to understand where this difference comes from.

For example, here's a simulated profile of a Cylindrical model given the following parameters:
![image](https://github.com/SASfit/SASfit/assets/48496966/c2809372-afad-4ca2-8702-35c1e2fdff1b)

and I get a 'decent' match in the shape shown on the left panel but the ratio between `Iq_SASFit/Iq_sasmodels` seems to be off by a pre-factor (that is also dependent on the q values)
![image](https://github.com/SASfit/SASfit/assets/48496966/ed35ea75-8486-46ca-bc7e-7d3f18fd633c).
Comparisons for other models (spherical, cylindrical, longrod) can be found [here](https://github.com/kiranvad/micelles/blob/main/notebooks/compare_sasfit_sasmodels.ipynb)

**Comment by Kohlbrecher** [comment]
I am not sure if SASfit uses the same formula to calculate the q-spacing then np.logspace. I assume you have the q values read in from the csv files. You should calculate the sasmodels with those values. The units of q are the  reciprocal of the length dimensions. There is no need for any unit conversion between sasmodels and SASfit. Just use exactly the same values. Could you check if there still exists a difference? You also could try to call the SASfit models from python. There is an example in the repository of how to do that. Maybe you like to try that?

**Comment by ibressler** [comment]
Hi kiranvad,

thanks for your report!

> My implementations match fairly well in terms of shape but are off by some form of pre-factor or volume normalization. I want to understand where this difference comes from.

That might be the case: I do not see in your notebook, how exactly the sasfit.csv was obtained and if/how it was processed before loading.

I should not here, that **SASfit exports number weighted distributions only**, no matter how the plot in the UI is configured.  It's a common misconception and we should make that more clear to the user.

For working with the results of various analysis programs and the most common stumbling blocks, I recommend [our current round robin paper on data analysis](https://doi.org/10.1107/S1600576723008324).

I hope this helps.

**Comment by Kohlbrecher** [comment]
I checked your code and compared it with the SASfit code. I do not immediately see a discrepancy between your and our code. Which version of SASfit do you use? I compared the code with the actual version. I am not that familiar with scripting SASview code from a jupyter notebook. Would you mind to focus on a single case? You stored several SASfit simulations in separate files and stored them in your repository but I do not exactly see, how you generated them with SASfit. You also could store a project file from SASfit which I can reload, so I see exactly, which parameters you have used. Those files typically get the extension *.sas. Nevertheless, it would help to focus on a single case at the beginning. 

PS: The factor 10^6 in the intensity likely comes from the fact, that you convert the q-values from A^-1 to nm^-1 and probably also changed all length units from A to nm. As the intensity is proportional to the volume square, i.e. proportional to R^6 a factor of 10 in length causes a factor 10^6 in intensity. By supplying a project file for your SASfit simulations I might better understand the reason for the difference in absolute scaling. I do not know if you have done any unit conversion for other parameters like the molecular volume of the Gaussian chains, etc. This is the reason why I suggested to use exactly the same parameters in SASfit then in your simulation. SASfit might write nm and nm^-1 on the axis, but internally it does not do any unit conversions. This is up to the user. There is a chapter (12) in the manual discussing this issue.

**Comment by kiranvad** [comment]
Thanks for the comments @Kohlbrecher ,
> Which version of SASfit do you use?

I am using the `SASfit-0.94.12-macos64` that I downloaded from the sasfit website

> As the intensity is proportional to the volume square, i.e. proportional to R^6 a factor of 10 in length causes a factor 10^6 in intensity.

I think this makes sense and I see less of that variance when I scale the I(q) from sasmodels by the total volume of the particle (see [here](https://github.com/kiranvad/micelles/blob/0738054e7d9c1039d5a4c9b6d9eae94ba7e4d486/models/cylindrical_micelle.py#L108)). Nevertheless, the discrepancies that are q-dependent continue to exist. Notably, the scale of this q-dependency also changes with the geometry of cylinders as can be seen [here](https://github.com/kiranvad/micelles/blob/main/notebooks/compare_sasfit_sasmodels.ipynb).

I have now added a separate notebook [here](https://github.com/kiranvad/micelles/blob/main/notebooks/sasfit_github_issue.ipynb) that compares it for a single system and also uploaded .sas project [here](https://github.com/kiranvad/micelles/blob/main/notebooks/SASFit/cyl_homogenous.sas) for your reference.

**Comment by Kohlbrecher** [comment]
I installed sasview myself and tried to understand your code.
In your models like spherical micelle or cylindrical micelle you divide everything by the molecular volume of the micelle "v_total". SASfit does not do this. Some people normalise the form factor on 1 for q=0. In that case you would need to divide by beta_tot = (beta_core+beta_corona)*n_aggreg. Than I have seen that you call your model via sasview library. I have seen, that that library adds by default an additional background to it. In your case of 0.001. Correcting for that (Iq_sasmodels = call_kernel(kernel, sphere_params)-0.001) I get in case of spheres in two case good agreement, however not for the middle one
![sph_brush](https://github.com/SASfit/SASfit/assets/11540933/fa47da24-f367-4711-a4d9-3721485c941b)
Could you check this part yourself already?

**Comment by Kohlbrecher** [comment]
PS: I used in the sasview model the same units as you used for SASfit namely nm and changed the q-range for plotting the data by a factor of 10 accordingly .

**Comment by Kohlbrecher** [comment]
Concerning the discrepancy for the cylindrical micelles I found that SASfit performs for an orientationally averaging an integration from 0 to pi/2. In the original paper in eq. 12 the same integration range is used. In your code you do an integration from 0 to pi as far as I understand (alpha = np.linspace(0, np.pi, num=100)). Please, could you also check this from your side?
It seems that your integration algorithm for orientationally averaging needs a lot of points being precise. If I increase the number of points from 100 to 1000 I get a fairly good agreement between your code and SASfit. Nevertheless I still need to remove the artificially added background value of 0.001 to get the following result:
![cyl_brush](https://github.com/SASfit/SASfit/assets/11540933/bf6955b5-5642-43d0-9854-1471beac139f)

**Comment by kiranvad** [comment]
Hi @Kohlbrecher,
Thanks for digging through this and for your input. These are super helpful and I think we have a better match now or understand where the discrepancies arise. 

Updated plots for comparison on my end can be found [here](https://github.com/kiranvad/micelles/blob/main/notebooks/compare_sasfit_sasmodels.ipynb). I still see some discrepancies for a few model/parameter combinations.
For example, it appears that for spherical micelles with homogenous contrast (left most plot on the first figure in the notebook) you had a better match than what I managed to get. It is very minimal but I am curious why would that be.

> In your models like spherical micelle or cylindrical micelle you divide everything by the molecular volume of the micelle "v_total". SASfit does not do this.

Okay, that makes sense. In general, I see a better match when I do not normalize by the total volume. 

> I have seen, that that library adds by default an additional background to it. In your case of 0.001.

That's a good point. I corrected my code and it resulted in an improved match.

> Concerning the discrepancy for the cylindrical micelles I found that SASfit performs for an orientationally averaging an integration from 0 to pi/2.
> If I increase the number of points from 100 to 1000 I get a fairly good agreement between your code and SASfit 

Both are important points and thanks for pointing it out. Again, I think they helped.

> In that case you would need to divide by beta_tot = (beta_core+beta_corona)*n_aggreg. 

I am curious about this. Can you expand on why would this be necessary?

**Comment by Kohlbrecher** [comment]
Some people like a normalised form factor so that I(q=0)=1, which you would get by normalising on beta_total. 
For the spherical micelle discrepancy I do not have an explanation yet. I checked your code by directly using your intensity function without using load_model. However, I could not find the problem. I also did not find the project file for that data file.

**Comment by Kohlbrecher** [comment]
For tests I often use the Gauss-Legendre Quadrature for integrating functions. It is straight forward in python (numpy). You probably find quickly an example for it and being able to use it with similar effort than in your example. However, you likely get already good results using less than 100 points.

**Comment by Kohlbrecher** [comment]
If I use a value for d equal 1.1 instead of 1 I get a good agreement for the corona contrast. Therefore it would be good to check the generation of the BlockCopolymerMicelle data by SASfit if there was a typo generating the data. It is unlikely as the full contrast data shows in that case a problem. Please, could you add that file as well.

**Comment by Kohlbrecher** [comment]
I mean the sasfit project file.

**Comment by kiranvad** [comment]
Hi @Kohlbrecher ,
Thanks for the comments. I did not save the project file for my simulations so there's no way to check that, unfortunately. But this discussion helped me in solving the issues so we can close it now. 

If I do find something odd to crop up in the future, I would comeback to this issue. Thanks for the help!

**Comment by Kohlbrecher** [comment]
If you make your work publicly available, please let me know.
