### ISSUE TITLE
SasFit build environment on Win7

### ISSUE THREAD

**Issue by EikeGericke** [SASfit/SASfit#2]
Guten Tag, 
ich habe versucht das SasFit über MINGW32 zu starten, um einen neuen Formfaktor in SasFIT einzubinden. 

Leider konnte /sasfit.dll nicht gefunden werden. 
Ich konnte diese Datei selbst auch nicht im gesamten Verzeichnis SASfit-master finden. 

Fehlt diese Datei eventuell? 

Ich habe den Ordner direkt von GitHub geladen. 

Mit besten Grüßen
Eike Gericke

![sasfit_issue](https://user-images.githubusercontent.com/33457837/32504814-03d6bb7c-c3e1-11e7-9e66-2440ddcbddb2.png)

**Comment by ibressler** [comment]
Hallo Eike, wenn dein Verzeichnis `SASfit-master` das Quellcode-Repository von github ist, dann existiert die Datei `sasfit.dll` noch nicht.

`sasfit.dll` wird erzeugt durch das Kompilieren von SASfit. Das musst du zunächst durchführen, um eigene Plugins zu entwickeln. [Hier ist das beschrieben.](http://sasfit.sf.net/manual/Overview:_Plugins#Recommended_Procedure)

In dem schwarzen Fenster mit der MSYS-Shell führst du folgende Befehle aus:
```
$ cd /c/ProgramUser/SASfit-Master
$ mkdir build
$ cd build
$ cmake ../src -G "MSYS Makefiles"
```
Dieser Befehl bereitet alles vor, um SASfit auf deinem System zu kompilieren: Es werden alle benötigten Bibliotheken und Pfadangaben zusammengesucht und auch abhängige Bibliotheken gebaut/kompiliert, die SASfit benötigt. Dieser Befehl war erfolgreich, wenn folgendes angezeigt wird:
```
   -- Configuring done
   -- Generating done
   -- Build files have been written to: <some path>
```
Anschließend gibst du `make` ein, um SASfit selbst zu kompilieren. 
```
$ make
```
Am Ende sollte eine `sasfit.exe` in `/c/ProgramUser/SASfit-Master` erscheinen.

**Comment by sylvainprevost** [comment]
Dear Ingo and Eike,

To my knowledge, since SASfit 0.94.6, it is not possible to compile SASfit with the programs from 'sasfit_build_environment_20131205.7z' due to inclusion of gsl 2.4 and sundials 2.7 that require newer CMake and gcc versions.

Although I was able to compile SASfit 0.94.7 with CMake 3.8 and mingw last June (GCC 5.3 I think), I am now unable to compile the latest git master, 0.94.9, 0.94.8 and 0.94.7 with CMake 3.9.4 and the latest mingw (GCC 6.3.0-1). In fact CMake already fails with the message:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FFTW_INCLUDE_DIRS
GSLCBLAS_STATIC_LIBRARY
GSL_INCLUDE_DIRS
GSL_STATIC_LIBRARY

```
If anyone has a different experience, I will be happy to hear from them.

Sylvain

**Comment by ibressler** [comment]
Over the last weeks I worked on building SASfit on Windows 10 x64 with MSYS2 (msys2.org) environment. This should work now when using the dedicated branch _saskit-update_. But this branch will not build on Linux or macOS yet - it is work in progress.

This is part of the effort, setting up a [continuous integration](https://en.wikipedia.org/wiki/Continuous_integration) pipeline for SASfit (like its standard for professional software development now) which works now for Windows x64. Latest build output can be seen/observed here: https://ci.appveyor.com/project/SASfit/sasfit

New commits pushed to the _saskit-update_ will be built automatically. I'll keep it in sync with the _master_ branch manually until that work is done (requiring it to work on the other platforms as well).
The resulting packages (development/experimental) are uploaded automatically to:
https://bintray.com/sasfit/development/SASfit
