### ISSUE TITLE
saskit build under MacOS failed

### ISSUE THREAD

**Issue by Kohlbrecher** [SASfit/SASfit#23]

**Comment by ibressler** [comment]
Not only saskit, also Tcl and sundials fail early:
https://ci.appveyor.com/project/SASfit/sasfit/builds/49811983/job/c0larba9ag51nqek?fullLog=true#L1532

https://ci.appveyor.com/project/SASfit/sasfit/builds/49811983/job/c0larba9ag51nqek?fullLog=true#L3650

Seems to be gcc v14 related, v13 worked.

**Comment by ibressler** [comment]
Pinning GCC to v13 on macOS in aa537b2c fixed it for now. What's the problem with gcc14 need more investigation.
