### ISSUE TITLE
Model LongCylShell does not produce any curve

### ISSUE THREAD

**Issue by ibressler** [SASfit/SASfit#4]
The model 'by plugins' -> 'cylindrical objects' -> LongCylShell does not produce any curve, e.g. for single data simulate/fit. Other models such as CylShell1 or CylShell2 do work fine instead. Observed with SASfit version 0.94.11 and also in the current development version.

(Reminder for me, as I can't look into it at the moment.)

**Comment by Kohlbrecher** [comment]
The model 'by plugins' -> 'cylindrical objects' -> LongCylShell is in
principle obsolete as a more general model is available under
'by plugins' -> 'thin obj.' -> 'local cylindrical obj.' -> Rod+SD+EllCylSh
Nevertheless LongCylShell should now returns meaningful values and not zero as before.
